spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/smartdocs
    username: user
    password: pass

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        options:
          model: qwen3:30b

      embedding:
        options:
          model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true

    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: chat_memory

  jpa:
    hibernate:
      ddl-auto: update
